### ISSUE TITLE
Check for "pencil" language

### ISSUE THREAD

**Issue by brianamarie** [githubtraining/managing-merge-conflicts#19]
Since updates have been made to the GitHub.com UI, the "edit" button is no longer a pencil. However, it will likely remain a pencil for users on older versions of GHES. We should update the instructions to be more inclusive regardless of version.

**Comment by parkerbxyz** [comment]
I'd just like to add that the pencil icon ( ![octicon-pencil] ) is still used as the "edit" button in some places on GitHub.com. It seems to be used primarily in the "Code" tab of repositories, but not the "Files Changed" tab in pull requests.

For what it's worth, I recently made a related change in the training manual and thought I'd share here the change in case it helps: githubtraining/training-manual@3c59c97 

[octicon-pencil]: https://unpkg.com/octicons/build/svg/pencil.svg

**Comment by brianamarie** [comment]
Thank you to @parkerbxyz for addressing this in #25! 🎉
